### ISSUE TITLE
Make this project's license more obvious

### ISSUE THREAD

**Issue by a1ro** [iacchus/birdears#45]
Looking at pypi's [project page](https://pypi.org/project/birdears/) or the output of `pip3 show birdears` once installed, I can see that birdears is licensed under MIT.

But on GitHub it is currently not obvious at all.
GitHub has a neat integration for licenses once properly setup.

An easy way to add one is from the project tabs: `Insights > Community > License > Propose`.
It should create a `LICENSE` file at the root of the project, and its page will have a header like this:

![license](https://user-images.githubusercontent.com/11812395/139749838-de428092-91a7-4da4-88bf-7cbd9faad05e.png)
Quite useful for people looking to contribute to the project.

**Comment by iacchus** [comment]
Thank you. I don't know why it was with MIT license; I set it to a GPL.

**Comment by a1ro** [comment]
Very clear now, thanks! And GPL seems more appropriate for an educational tool.
