### ISSUE TITLE
No module named 'click'

### ISSUE THREAD

**Issue by BasT94** [iacchus/birdears#5]
Hello, and thanks for the software. As a music student, I'm very interested in having an application such as this one. I know there are others on the internet, but I didn't found what I was looking for exactly. That is, that when I get tested with harmonic intervals, I don't merely have to answer what kind of interval it is, but also sing it. This way, I get trained at separating the sounds in my mind. And after singing it, I can verify whether I got the sounds right (sort of like having the app have an option to arpeggiate the interval.) I realize that birdears is probably unable to do that as of yet, so I was also inclined to aid in its development or at least modify it to suit my needs, however I barely began to study programing yesterday, when I found this software. I also can't make it work, which is why I made this thread.

This is what happens. I run it on cmd by writing "birdears --help" (as you said), and get this:

Traceback (most recent call last):
  File "c:\users\diógenes samuel\appdata\local\programs\python\python36\lib\runp
y.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\diógenes samuel\appdata\local\programs\python\python36\lib\runp
y.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Diógenes Samuel\AppData\Local\Programs\Python\Python36\Scripts\
birdears.exe\__main__.py", line 5, in <module>
  File "c:\users\diógenes samuel\appdata\local\programs\python\python36\lib\site
-packages\birdears\__main__.py", line 3, in <module>
    from . import click
  File "c:\users\diógenes samuel\appdata\local\programs\python\python36\lib\site
-packages\birdears\click\__init__.py", line 18, in <module>
    from .core import Context, BaseCommand, Command, MultiCommand, Group, \
  File "c:\users\diógenes samuel\appdata\local\programs\python\python36\lib\site
-packages\birdears\click\core.py", line 8, in <module>
    from .types import convert_type, IntRange, BOOL
  File "c:\users\diógenes samuel\appdata\local\programs\python\python36\lib\site
-packages\birdears\click\types.py", line 4, in <module>
    from ._compat import open_stream, text_type, filename_to_ui, \
  File "c:\users\diógenes samuel\appdata\local\programs\python\python36\lib\site
-packages\birdears\click\_compat.py", line 539, in <module>
    from ._winconsole import _get_windows_console_stream
  File "c:\users\diógenes samuel\appdata\local\programs\python\python36\lib\site
-packages\birdears\click\_winconsole.py", line 18, in <module>
    from click._compat import _NonClosingTextIOWrapper, text_type, PY2
ModuleNotFoundError: No module named 'click'

I'm a noob at this, so I don't know what to do. I ran _winconsole.py in from Python 3.6, and saw this:

from click._compat import _NonClosingTextIOWrapper, text_type, PY2

However, I don't find any files named "click". Now, I'm not sure if that's what's really needed, but since what I've found is that when you use "from" and then "import" you're esentially calling a function or plugin inside something, if the something you're calling it from isn't there, well...

Anyway, I'm not sure, so I came for help. I might have gotten something wrong during the installation or something. Hopefully it's easy to fix.

Thanks for the effort anyway.

**Comment by iacchus** [comment]
Hello, did you managed to fix the issue?

The `click` module is a third-party module who handles the command line interface of birdears. BUT it is shipped within the package. I am unable to reproduce the error because I wrote it in an arch linux (it as tested also in an Ubuntu linux via TravisCI) and don't have any Windows machine to try it out.

I think that if you install the `click` package  with `pip3 install click` it should work, but it would be better if we could fix this issue by fixing birdears (or your PYTHONPATH if that be the case) and you could use the embedded version of `click`.

Now I see here, the module click is being found by birdears, but the error is within the windows compatibility part of it.
